### ISSUE TITLE
Add Robot Tests for hover

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/jupyterlab-lsp#297]
## Elevator Pitch

We should test hover behaviors.

## Motivation

Hover is an important feature for understanding code that should be pretty responsive.

## Design Ideas

- In `01_Editor.robot`, each server that supports hover should have a `hover=Message here`. 
- A new keyword, `Editor Shows Hover  ${selector}   ${message}`. Maybe have a configurable timeout... some language servers probably have a cache.

**Comment by krassowski** [comment]
Working on this now, will PR soon (though not for all servers and in notebooks only - feel free too pick up and add tests in `01_Editor.robot` afterwards!)

**Comment by krassowski** [comment]
Kind of depends on https://github.com/robotframework/SeleniumLibrary/issues/1639.

Though I think we could have a setting to show the hover tooltip after `n` seconds anyways. `n > 5`

**Comment by bollwyvl** [comment]
Action chains do work, but are non-obvious... I had to ctrl+shift drag
something once (nightmares). I'll see i can dig it up.

**Comment by krassowski** [comment]
Actually I just realised that I implemented hover in the way that it is sufficient to press the modifier after hover to bring the tooltip up, which is intended so that the user does not have to move the mouse again :)

**Comment by krassowski** [comment]
Extracted the idea of adding delay-based activation to #362.

**Comment by krassowski** [comment]
As of today hover is tested in `Hover.robot`:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/7ae3c056ed5092b8081719138ead8d12902434e5/atest/05_Features/Hover.robot#L13-L45

This issue proposed to add a basic test of hover per-server. Given the simplicity of this feature I am not convinced it is necessary; I do think that testing some features for all supported servers is a good thing (e.g. diagnostics as a sanity check "is this server working" + rename because it is very complex) just not sure if the added burden of adding hover to the list is worth it -> I will not be working on it, but if anyone wants to, I am happy to review the pull request :)
