### ISSUE TITLE
Support %%time

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter-lsp/jupyterlab-lsp#635]
## Elevator Pitch

Code defined in a `%%time` cell doesn't appear to be recognised so you then get spurious warnings about e.g. undefined variables.

![image](https://user-images.githubusercontent.com/881019/123722787-625b2300-d8cc-11eb-8860-1b046654f495.png)

## Motivation

Spurious warnings detract from the utility of a code linter

## Design Ideas

I think this is a hard problem to solve as shown by other issues about magic commands.  All I can think of is enumeratig a bunch of special cases 🤢.  Maybe that's not so bad though - just like a `.gitignore` file enumerates a bunch of patterns to ignore, `jupyterlab-lsp` could have a configuration for magics which allowed a user to specify what it should do (e.g. ignore). This would then cater for all custom user-defined magics as well.

**Comment by krassowski** [comment]
We can solve this relatively easily. This is because we already transform cell magics to equivalent Python commands; for example

```
%%script bash
echo "2"
ls
```

becomes:

```python
get_ipython().run_cell_magic("script", "bash", """echo 2
ls""")
```

we _only_ need to use a different transformation for some magics (`%%capture`, `%%time` but not `%%timeit`; we need to create list of those, and allow users to customize this list in the future) which execute the code in the same namespace as the parent notebook. For example:

```
%%capture --no-display
x = 2
```

would become:

```python
# START_CELL_MAGIC("capture", "--no-display")
x = 2
# END_CELL_MAGIC
```

The current code that does the transformation is in:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/e83d8e6bae2838eeb046805b51503c11b109aa2a/packages/jupyterlab-lsp/src/transclusions/ipython/overrides.ts#L122-L146
