### ISSUE TITLE
How to load the "help" information?

### ISSUE THREAD

**Issue by hellojinwoo** [jupyter-lsp/jupyterlab-lsp#744]
![image](https://user-images.githubusercontent.com/34431729/148252552-a16645e5-1ff0-482f-8464-c4c5cbe27517.png)

Sometime when I type coding, the help information, which is shown above, randomly appears. How can I load that information when I want to? Which key do I need to use, in order to load the information like the one above?

**Comment by hellojinwoo** [comment]
> This triggers on a set of keys pre-defined by the server, so it will differ by language and between servers; for pylsp/jedi-ls/pyright it includes `(` and `,` keys among others; it remains open as long as the server decides it should be open (based on your cursor position).

Can you tell me why sometimes the documentation information appears and sometimes it does not?
Let me give you an example. 

```
import pandas as pd

df = pd.DataFrame({'symbol': {pd.Timestamp('2021-10-26 00:00:00'): 'BTCUSDT',
                              pd.Timestamp('2021-10-26 00:05:00'): 'BTCUSDT',
                              pd.Timestamp('2021-10-26 00:10:00'): 'BTCUSDT'},
                   'account': {pd.Timestamp('2021-10-26 00:00:00'): 0.6558,
                               pd.Timestamp('2021-10-26 00:05:00'): 0.6559,
                               pd.Timestamp('2021-10-26 00:10:00'): 0.672},
                    'ratio': {pd.Timestamp('2021-10-26 00:00:00'): 1.9053,
                              pd.Timestamp('2021-10-26 00:05:00'): 1.9061,
                              pd.Timestamp('2021-10-26 00:10:00'): 2.0488}})
```

Now what I want to do is reading the documentation `pd.to_localize()` while typing `df.to_localize("UST")`. 
We do have the documentation page of [pd.to_localize()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tz_localize.html) in the pandas website. 

However, when I typed `df.to_localize(` without closing the parenthesis, nothing appears. You can check it out in the screenshot below as well.
![image](https://user-images.githubusercontent.com/34431729/148256072-968a2e93-aa54-4139-aa5d-47ff3cc684fd.png)

Why does the documentation information appears for `pd.DataFrame(` but not for `df.to_localize(` ?

**Comment by krassowski** [comment]
There is no forced latency (no debouncer or throttler) on signature feature, so I'm afraid the slowness is on the server side. If there is a performance bottleneck which can be narrowed down to a specific scenario and persists when using different servers, please provide reproduction instructions so that we can fix it.

Also, some general performance improvements to diagnostics and highlights were just added in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/847 (and performance of diagnostics and highlights might have been impacting signature display if these features were active at the same time in certain scenarios).
