### ISSUE TITLE
How to use relative paths in configuration?

### ISSUE THREAD

**Issue by fhg-isi** [jupyter-lsp/jupyterlab-lsp#983]
## What I am trying to do...

I try to reference a pyproject.toml file containing pyling settings. 
I would like to reference it relative to the notebook directory, for example:

`"pylsp.plugins.pylint.args": ["--rcfile $notebook_directory$/pyproject.toml"],`

That would allow me to move my portable python IDE to a different folder and still keep the reference working. 

## How I would like to learn how to do it...

Could you please include a comment about relative paths in the documentation of the configuration
and clarify if some variables exist that could be used as a reference for relative paths.

**Comment by krassowski** [comment]
Is `$notebook_directory` = folder where you start JupyterLab?

If so we should implement `pyproject.toml` detection in `python-lsp-server` and then it would work without any configuration. We do that for pycodestyle and flake8 so why not for pylint. Please open an issue and PR over on https://github.com/python-lsp/python-lsp-server

**Comment by fhg-isi** [comment]
a) Exactly, I refer to the --notebook-dir argument https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html.

b) If I understand you correctly, currently no path variables are supported in the configuration.

c) Automatic detection also would be fine.

**Comment by krassowski** [comment]
Great! I will close this issue then because this needs to be resolved on the language server side.

(b) we do not touch the configuration at all in jupyterlab-lsp, just forward it to the language server as-is. python-lsp-server just forwards them to pyliny as-is. pylint might have some path variable expansion but you would need to check.

(c) then please follow up in the python-lsp-server repository :)
